name: Docker multiarch publish

on:
  push:
    tags:
      - "v*"

jobs:
  buildandpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
<<<<<<< HEAD
<<<<<<< HEAD
        uses: actions/checkout@v2.3.4
=======
        uses: actions/checkout@v2.4.0
>>>>>>> 0d67841370c3f33b1741fd109159675044c93eb6
=======
        uses: actions/checkout@v3.0.2
>>>>>>> 13ee4ee2732ad44af7c237c4b27bf79ecf9e49f6

      # https://github.com/martinbeentjes/npm-get-version-action
      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      # https://github.com/booxmedialtd/ws-action-parse-semver
      - name: Parse version
        id: semver-version
        uses: booxmedialtd/ws-action-parse-semver@v1.4.5
        with:
          input_string: ${{ steps.package-version.outputs.current-version}}

      # https://github.com/docker/setup-qemu-action#usage
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/build-push-action#multi-platform-image
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.semver-version.outputs.major }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.semver-version.outputs.major }}.${{ steps.semver-version.outputs.minor }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.semver-version.outputs.fullversion }}
